export const posts = [
  {
    id: 21,
    src: "/flower_achive/post_21.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 20,
    src: "/flower_achive/post_20.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 19,
    src: "/flower_achive/post_19.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 18,
    src: "/flower_achive/post_18.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 17,
    src: "/flower_achive/post_17.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 16,
    src: "/flower_achive/post_16.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 15,
    src: "/flower_achive/post_15.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 14,
    src: "/flower_achive/post_14.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 13,
    src: "/flower_achive/post_13.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 12,
    src: "/flower_achive/post_12.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 11,
    src: "/flower_achive/post_11.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 10,
    src: "/flower_achive/post_10.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 9,
    src: "/flower_achive/post_9.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 8,
    src: "/flower_achive/post_8.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 7,
    src: "/flower_achive/post_7.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 6,
    src: "/flower_achive/post_6.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 5,
    src: "/flower_achive/post_5.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 4,
    src: "/flower_achive/post_4.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 3,
    src: "/flower_achive/post_3.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 2,
    src: "/flower_achive/post_2.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 1,
    src: "/flower_achive/post_1.png",
    likes: 1,
    comments: 1,
  },
  {
    id: 0,
    src: "/flower_achive/post_0.png",
    likes: 1,
    comments: 1,
  },
];
